package bluej.extensions;

/**
 * Base class for the different Exception event generated by BlueJ for extensions.
 * 
 * @version $Id: ExtensionException.java 1967 2003-05-21 09:10:02Z damiano $
 */
public class ExtensionException extends Exception 
  {
  ExtensionException ( String reason )
    {
    super (reason);
    }
  
  }