package bluej.extensions;

/**
 * Base class for the different Exception event generated by BlueJ for extensions.
 * 
 * @version $Id: ExtensionException.java 1982 2003-05-23 08:08:34Z damiano $
 */
public class ExtensionException extends Exception 
{
    ExtensionException ( String reason ) {
        super (reason);
        }
  
}