/*
 This file is part of the BlueJ program.
 Copyright (C) 2026  Michael Kolling and John Rosenberg

 This program is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License
 as published by the Free Software Foundation; either version 2
 of the License, or (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

 This file is subject to the Classpath exception as provided in the
 LICENSE.txt file that accompanied this code.
 */
package bluej.views;

import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import bluej.utility.Debug;

import kotlin.Metadata;
import kotlin.metadata.Attributes;
import kotlin.metadata.KmClass;
import kotlin.metadata.KmClassifier;
import kotlin.metadata.KmPackage;
import kotlin.metadata.KmProperty;
import kotlin.metadata.KmType;
import kotlin.metadata.jvm.KotlinClassMetadata;

/**
 * Reads {@code @kotlin.Metadata} from a compiled Kotlin class and returns
 * the set of method names that are compiler-generated property accessors.
 *
 * @author BlueJ Team
 */
public final class KotlinPropertyAccessorDetector
{
    private KotlinPropertyAccessorDetector()
    {
        // Utility class — not instantiable
    }

    /**
     * Returns the set of method names (e.g. "getName", "setAge", "isActive")
     * that are auto-generated property accessors for the given class.
     * Returns an empty set for non-Kotlin classes (no {@code @kotlin.Metadata}).
     *
     * <p>If metadata parsing fails, a warning is logged and an empty set is
     * returned — graceful degradation to unlabelled methods.
     *
     * @param cl  the compiled class to inspect
     * @return    unmodifiable set of auto-generated accessor method names
     */
    public static Set<String> getAutoGeneratedAccessorNames(Class<?> cl)
    {
        Metadata metadata = cl.getAnnotation(Metadata.class);
        if (metadata == null) {
            return Collections.emptySet();
        }

        try {
            KotlinClassMetadata kcm = KotlinClassMetadata.readStrict(metadata);

            // Extract properties from either a class or a file facade (top-level declarations)
            List<KmProperty> properties;
            if (kcm instanceof KotlinClassMetadata.Class) {
                properties = ((KotlinClassMetadata.Class) kcm).getKmClass().getProperties();
            }
            else if (kcm instanceof KotlinClassMetadata.FileFacade) {
                properties = ((KotlinClassMetadata.FileFacade) kcm).getKmPackage().getProperties();
            }
            else {
                return Collections.emptySet();
            }

            Set<String> accessorNames = new HashSet<>();
            for (KmProperty property : properties) {
                addAccessorNames(property, accessorNames);
            }

            return Collections.unmodifiableSet(accessorNames);
        }
        catch (Exception e) {
            Debug.reportError("Failed to parse Kotlin metadata for " + cl.getName(), e);
            return Collections.emptySet();
        }
    }

    /**
     * Adds the getter and (if applicable) setter method names for a property.
     *
     * <p>Kotlin naming conventions:
     * <ul>
     *   <li>Property {@code foo} → getter {@code getFoo()}, setter {@code setFoo()}</li>
     *   <li>Boolean property {@code isActive} → getter {@code isActive()}, setter {@code setActive()}</li>
     * </ul>
     */
    private static void addAccessorNames(KmProperty property, Set<String> accessorNames)
    {
        String name = property.getName();
        boolean isBooleanIs = isBooleanIsProperty(property);

        // Getter name
        if (isBooleanIs) {
            // Boolean property with "is" prefix: getter IS the property name
            accessorNames.add(name);
        }
        else {
            accessorNames.add("get" + capitalize(name));
        }

        // Setter name (only for var, not val)
        if (Attributes.isVar(property)) {
            if (isBooleanIs) {
                // Boolean "is" property: setter replaces "is" with "set"
                accessorNames.add("set" + name.substring(2));
            }
            else {
                accessorNames.add("set" + capitalize(name));
            }
        }
    }

    /**
     * Checks whether a property uses the Boolean "is"-prefix naming convention.
     * This applies when the name starts with "is" + uppercase and the return
     * type is {@code kotlin.Boolean}.
     */
    private static boolean isBooleanIsProperty(KmProperty property)
    {
        String name = property.getName();
        if (!name.startsWith("is") || name.length() <= 2
                || !Character.isUpperCase(name.charAt(2))) {
            return false;
        }

        KmType returnType = property.getReturnType();
        if (returnType == null) {
            return false;
        }

        KmClassifier classifier = returnType.getClassifier();
        if (classifier instanceof KmClassifier.Class) {
            String className = ((KmClassifier.Class) classifier).getName();
            return "kotlin/Boolean".equals(className);
        }
        return false;
    }

    private static String capitalize(String name)
    {
        if (name == null || name.isEmpty()) {
            return name;
        }
        return Character.toUpperCase(name.charAt(0)) + name.substring(1);
    }
}
