#!/bin/sh

unset JAVAPATH
JAVAPATH="/usr/share/greenfoot/jdk"
CP="/usr/share/greenfoot/boot.jar"
JAVAFXJARS=`ls -1 /usr/share/greenfoot/javafx* | paste -sd ":" -`
CP="$CP:$JAVAFXJARS"

"$JAVAPATH/bin/java" -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2 -Djdk.gtk.version=2 -Dawt.useSystemAAFontSettings=on -Xmx512M \
    -cp "$CP" bluej.Boot \
    -greenfoot=true -bluej.compiler.showunchecked=false \
    -greenfoot.scenarios=/usr/share/doc/Greenfoot/scenarios \
    -greenfoot.url.javadoc=file:///usr/share/doc/Greenfoot/API/ \
    "$@"

