package bluej.groupwork;

import java.util.ArrayList;
import java.util.List;

import org.netbeans.lib.cvsclient.command.FileInfoContainer;
import org.netbeans.lib.cvsclient.command.log.LogInformation;
import org.netbeans.lib.cvsclient.event.FileInfoEvent;

import bluej.groupwork.cvsnb.BasicServerResponse;

/**
 * A reponse handler for the "cvs log" command. Keeps a list of responses
 * generated by the server.
 * 
 * @author Davin McCall
 * @version $Id: LogServerResponse.java 4926 2007-04-13 02:28:18Z davmac $
 */
public class LogServerResponse extends BasicServerResponse
{
    private List infoList;
    
    public LogServerResponse()
    {
        infoList = new ArrayList();
    }
    
    public void fileInfoGenerated(FileInfoEvent arg0)
    {
        FileInfoContainer fic = arg0.getInfoContainer();
        if (fic instanceof LogInformation) {
            infoList.add(fic);
        }
    }
    
    public List getInfoList()
    {
        return infoList;
    }
}
