#!/bin/sh

unset JAVAPATH
JAVAPATH="/usr/share/bluej/jdk"
CP="/usr/share/bluej/boot.jar"
JAVAFXJARS=`ls -1 /usr/share/bluej/javafx* | paste -sd ":" -`
CP="$CP:$JAVAFXJARS"

"$JAVAPATH/bin/java" -Djdk.gtk.version=2 -Dawt.useSystemAAFontSettings=on -Xmx512M -cp "$CP" bluej.Boot "$@"
