#!/bin/sh

unset JAVAPATH
JAVAPATH="/usr/share/bluej/jdk"
JAVAFXPATH="/usr/share/bluej/javafx"
CP="/usr/share/bluej/bluej.jar"
JAVAFXJARS="$JAVAFXPATH/lib/javafx.base.jar"
JAVAFXJARS="$JAVAFXJARS:$JAVAFXPATH/lib/javafx.controls.jar"
JAVAFXJARS="$JAVAFXJARS:$JAVAFXPATH/lib/javafx.fxml.jar"
JAVAFXJARS="$JAVAFXJARS:$JAVAFXPATH/lib/javafx.graphics.jar"
JAVAFXJARS="$JAVAFXJARS:$JAVAFXPATH/lib/javafx.media.jar"
JAVAFXJARS="$JAVAFXJARS:$JAVAFXPATH/lib/javafx.properties.jar"
JAVAFXJARS="$JAVAFXJARS:$JAVAFXPATH/lib/javafx.swing.jar"
JAVAFXJARS="$JAVAFXJARS:$JAVAFXPATH/lib/javafx.web.jar"
CP="$CP:$JAVAFXJARS"
JFXRTOPT="-javafxpath=$JAVAFXPATH"
JFXRTOPT2="-javafxjars=$JAVAFXJARS"

"$JAVAPATH/bin/java" -Dawt.useSystemAAFontSettings=on -Xmx512M \
    -cp "$CP" bluej.Boot ${JFXRTOPT:+"$JFXRTOPT"} ${JFXRTOPT2:+"$JFXRTOPT2"} "$@"
