// Do not edit. This file is machine generated by the Resource DLL Wizard.

library vmselect;

{$R *.RES}
{ITE} {LCID:00000C09:00000405} {}
{ITE} {DFMFileType} {main.dfm}
{ITE} {RCFileType} {vmselect_DRC.rc}

{$R 'main.dfm' MainForm:TForm}
{$R 'vmselect_DRC.res' 'vmselect_DRC.rc'}

{$E CSY}

begin
end.