package bluej.extensions.event;

import java.io.File;

/**
 * This class encapsulates compiler events.
 * It allows an extension writer to know when a compilation starts and
 * finishes, whether it succeeds or fails, and what warnings or errors are 
 * generated. The order of occurence of the various types of this event is:
 * <pre>
 *     COMPILATION_START_EVENT
 *     COMPILE_ERROR_EVENT                        # If a compilation error occurs
 *     COMPILE_WARNING_EVENT                      # If a compilation warning occurs
 *     COMPILE_FAILED_EVENT or COMPILE_DONE_EVENT
 * </pre>
 * Note that currently BlueJ only reports the first compilation error or warning.
 * 
 * @version $Id: CompileEvent.java 1885 2003-04-25 08:53:48Z damiano $
 */

/*
 * Author Damiano Bolla, University of Kent at Canterbury, 2003
 */
public class CompileEvent implements ExtensionEvent 
{
  /**
   * Event generated when compilation begins
   */
  public static final int COMPILE_START_EVENT=1;

  /**
   * Event generated when a compilation warning occurs.
   * A warning event is one that will not invalidate the compilation.
   */
  public static final int COMPILE_WARNING_EVENT=2;

  /**
   * Event generated when a compilation error occurs.
   * An error event is one that will invalidate the compilation
   */
  public static final int COMPILE_ERROR_EVENT=3;

  /**
   * Event generated when a compilation finishes successfully.
   */
  public static final int COMPILE_DONE_EVENT=4;

  /**
   * Event generated when a compilation finishes unsuccessfully.
   */
  public static final int COMPILE_FAILED_EVENT=5;

  private int    eventId;
  private File[] fileNames;   // An array of names this event belong to
  private int    errorLineNumber;
  private String errorMessage;

  /**
   * Constructor for a CompileEvent.
   */
  public CompileEvent(int anEventId, File[] aFileNames)
    {
    eventId   = anEventId;
    fileNames = aFileNames;
    }

  /**
   * Returns the eventId, one of the values defined.
   */
  public int getEvent ()
    {
    return eventId;
    }


  /**
   * Returns an array of zero, one or more files related to this event.
   * In the case of an error or warning event it is normally a one element array.
   * In all other cases it depends on the number of files being compiled.
   */
  public File[] getFiles ()
    {
    return fileNames;
    }

  /**
   * Sets the line number where an error or warning occurred.
   */
  public void setErrorLineNumber ( int aLineNumber )
    {
    errorLineNumber = aLineNumber;
    }

  /**
   * Returns the line number where the compilation error occurs.
   * Only valid in the case of an error or warning event.
   */
  public int getErrorLineNumber ( )
    {
    return errorLineNumber;
    }

  /**
   * Sets the error message for an error or warning event.
   */
  public void setErrorMessage ( String anErrorMessage )
    {
    errorMessage = anErrorMessage;
    }
  
  /**
   * Returns the error message generated by the compiler.
   * Only valid in the case of an error or warning event.
   */
  public String getErrorMessage ( )
    {
    return errorMessage;
    }

  /**
   * Returns a meaningful description of this event.
   */
  public String toString()
    {
    StringBuffer aRisul = new StringBuffer (500);

    aRisul.append("CompileEvent:");

    if ( eventId == COMPILE_START_EVENT ) aRisul.append(" COMPILE_START_EVENT");
    if ( eventId == COMPILE_WARNING_EVENT ) aRisul.append(" COMPILE_WARNING_EVENT");
    if ( eventId == COMPILE_ERROR_EVENT ) aRisul.append(" COMPILE_ERROR_EVENT");
    if ( eventId == COMPILE_DONE_EVENT ) aRisul.append(" COMPILE_DONE_EVENT");
    if ( eventId == COMPILE_FAILED_EVENT ) aRisul.append(" COMPILE_FAILED_EVENT");

    aRisul.append(" getFiles()[0]=");
    aRisul.append(fileNames[0]);

    if ( eventId == COMPILE_WARNING_EVENT || eventId == COMPILE_ERROR_EVENT )
      {
      aRisul.append(" errorLineNumber="+errorLineNumber);
      aRisul.append(" errorMessage="+errorMessage);
      }

    return aRisul.toString();
    }
}
