/*
 This file is part of the BlueJ program.
 Copyright (C) 1999-2009,2014,2016,2017,2018,2020  Michael Kolling and John Rosenberg

 This program is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License
 as published by the Free Software Foundation; either version 2
 of the License, or (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

 This file is subject to the Classpath exception as provided in the
 LICENSE.txt file that accompanied this code.
 */
package bluej.classmgr;

import org.objectweb.asm.ClassReader;
import org.objectweb.asm.tree.ClassNode;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

public class ClassFileReader {
    /**
     * Reads the source file name from the specified compiled class file (the `SourceFile` attribute).
     * This attribute is optional and may be absent from the class file,
     * but it is usually generated by the Kotlin compiler and Java compiler (in debug mode).
     *
     * @param classFile the class file to read from; must not be null and should reference a valid class file.
     * @return the name of the source file associated with the class, or null if the class file does not contain
     *         this information or if an I/O error occurs.
     */
    public static String readSourceFileField(File classFile) {
        try (InputStream in = new FileInputStream(classFile)) {
            ClassReader reader = new ClassReader(in);
            ClassNode node = new ClassNode();
            reader.accept(node, 0);
            return node.sourceFile;
        } catch (IOException e) {
            return null;
        }
    }
}